version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    # Using selective volume mounting for the src directory only
    volumes:
      - ./frontend/src:/app/src:delegated
    # Using the non-root user from your Dockerfile
    user: "appuser:appgroup"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/taskmanager
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"  # Changed from 3306:3306 to 3307:3306
    environment:
      - MYSQL_DATABASE=taskmanager
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: